version: '3'

tasks:
  'core:run':
    dir: core
    cmds:
      - cargo run
  
  'core:lint':
    dir: core
    cmds:
      - cargo clippy
    
  'core:fmt':
    dir: core
    cmds:
      - cargo fmt
  
  'web:run':
    dir: web
    cmds:
      - npm start
  
  'web:build':
    dir: web
    cmds:
      - npm run build
  
  'extension:build':
    dir: extension
    cmds:
      - npm run build