version: "3"

tasks:
  "protoc:gen:web":
    internal: true
    cmds:
      - docker run -v {{.TASKFILE_DIR}}/proto:/proto -v {{.OUTPUT_DIR}}:/out namely/protoc-all -d /proto -o /out -l web

  "core:build":
    dir: core
    cmds:
      - cargo build --release

  "core:run":
    dir: core
    cmds:
      - cargo run

  "core:lint":
    dir: core
    cmds:
      - cargo clippy
  
  "core:lint:fix":
    dir: core
    cmds:
      - cargo clippy --fix --allow-dirty

  "core:fmt":
    dir: core
    cmds:
      - cargo fmt

  "web:proto":
    cmds:
      - task: "protoc:gen:web"
        vars:
          OUTPUT_DIR: "{{.TASKFILE_DIR}}/web/src/proto"

  "web:run":
    deps: ["web:proto"]
    dir: web
    cmds:
      - npm start

  "web:build":
    deps: ["web:proto"]
    dir: web
    cmds:
      - rm -rf ./dist
      - npm i
      - npm run build

  "extension:proto":
    cmds:
      - task: "protoc:gen:web"
        vars:
          OUTPUT_DIR: "{{.TASKFILE_DIR}}/extension/src/proto"

  "extension:build":
    deps: ["extension:proto"]
    dir: extension
    cmds:
      - rm -rf ./dist
      - npm i
      - npm run build

  "proto":
    cmds:
      - task: "web:proto"
      - task: "extension:proto"

  "build":
    cmds:
      - task: "core:build"
      - task: "web:build"
      - task: "extension:build"

  "fmt":
    cmds:
      - task: "core:fmt"

  "core:up":
    cmds:
      - docker-compose -f ./infra/dev/docker-compose.yml up -d --build
      - task: "core:run"
