[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
prost = "0.11.9"
regex = "1.8.3"
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.9.2"
tonic-web = "0.9.2"

[build-dependencies]
tonic-build = "0.9.2"
