[package]
name = "core"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
anyhow = "1.0.71"
chrono = { version = "0.4.24", features = ["serde"] }
config = "0.13.3"
dotenv = "0.15.0"
futures = "0.3.28"
lazy_static = "1.4.0"
prost = "0.11.9"
r2d2 = "0.8.10"
rayon = "1.7.0"
redis = { version = "0.23.0", features = ["json", "r2d2", "tls-native-tls"] }
regex = "1.8.3"
rust-s3 = "0.33.0"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
tl = "0.7.7"
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.9.2"
tonic-web = "0.9.2"
ulid = { version = "1.0.0", features = ["serde"] }

[build-dependencies]
tonic-build = "0.9.2"
