[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.24"
config = "0.13.3"
dotenv = "0.15.0"
lazy_static = "1.4.0"
prost = "0.11.9"
r2d2 = "0.8.10"
redis = { version = "0.23.0", features = ["json", "r2d2", "tls-native-tls"] }
regex = "1.8.3"
serde = "1.0.163"
serde_derive = "1.0.163"
tokio = { version = "1.28.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.9.2"
tonic-web = "0.9.2"
ulid = "1.0.0"

[build-dependencies]
tonic-build = "0.9.2"
