permissions:
  packages: write
  contents: read
  id-token: write
on:
  - push
  - pull_request
name: workflow
env:
  IMAGE_NAME: ghcr.io/shedrachokonofua/lute-v4:${{ github.sha }}
  IMAGE_NAME_ARM: ghcr.io/shedrachokonofua/lute-v4:${{ github.sha }}-arm
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: true
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.1

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

      - name: Install QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build Docker Images
        run: |
          echo "Image names: ${{ env.IMAGE_NAME }}, ${{ env.IMAGE_NAME_ARM }}"
          docker build -t ${{ env.IMAGE_NAME }} -f core/Dockerfile .
          docker buildx create --use --name builder
          docker buildx build --platform linux/arm64 -t ${{ env.IMAGE_NAME_ARM }} -f core/Dockerfile.arm .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push ${{ env.IMAGE_NAME }}
          docker buildx build --build-arg TARGET_CORES=4 --platform linux/arm64 --push -t ${{ env.IMAGE_NAME_ARM }} .
