permissions:
  packages: write
  contents: read
  id-token: write
on:
  - push
  - pull_request
name: workflow
env:
  IMAGE_NAME: ghcr.io/shedrachokonofua/lute-v4:${{ github.sha }}
  IMAGE_NAME_ARM: ghcr.io/shedrachokonofua/lute-v4:${{ github.sha }}-arm
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/docker-layers
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile*') }}
          restore-keys: ${{ runner.os }}-docker-

      - name: Build x86 Docker Image
        run: |
          echo "Image name: ${{ env.IMAGE_NAME }}"
          docker build -t ${{ env.IMAGE_NAME }} -f core/Dockerfile .

      - name: Build ARM Docker Image
        run: |
          echo "Image name: ${{ env.IMAGE_NAME_ARM }}"
          docker build -t ${{ env.IMAGE_NAME_ARM }} -f core/Dockerfile.arm .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME_ARM }}
